### ISSUE TITLE
Mulitprocessing issue

### ISSUE THREAD

**Issue by bntr00t** [MHProDev/MHDDoS#118]
Python 3.9.10, Win 10 21H2

{'type': 1, 'url': 'https://api.proxyscrape.com/?request=displayproxies&proxytype=http', 'timeout': 5}
{'type': 1, 'url': 'https://www.proxy-list.download/api/v1/get?type=http', 'timeout': 5}
{'type': 1, 'url': 'https://www.proxyscan.io/download?type=http', 'timeout': 5}
{'type': 1, 'url': 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt', 'timeout': 5}
2,749 Proxies are getting checked, this may take awhile !
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 519, in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 499, in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 884, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Users\bnt\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 816, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 502

**Comment by MHProDev** [comment]
fixed
