### ISSUE TITLE
BUG python3.10

### ISSUE THREAD

**Issue by DemOnJR** [MHProDev/MHDDoS#193]
**Describe the bug**
Layer 4
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/root/bogdan/ta/start.py", line 91, in __init__
    super().__init__(daemon=True)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```
Layer 7
```
Traceback (most recent call last):
  File "/root/bogdan/ta/start.py", line 924, in <module>
    daemon=True).start()
  File "/usr/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

**Please complete the following information**
 - OS: Ubuntu
 - Python Version 3.10

**Comment by fnnzzz** [comment]
Solution: https://bit.ly/3hEbSpG

**Comment by SlimJUC** [comment]
what is the command ur trying to use to run the attack
