### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by terion-name** [MHProDev/MHDDoS#202]
```
sudo python3 start.py dns 1.2.3.4:443 128 604800 dns.txt true
```
```
Exception in thread Thread-116:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "start.py", line 187, in run
    self.select(self._method)
  File "start.py", line 236, in select
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 333, in _generate_amp
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
```

files/dns.txt is present and valid

**Comment by MHProDev** [comment]
https://github.com/MHProDev/MHDDoS/commit/0dbbc99a4e7ba2828a9167a5a40cd199cc24116e
try with this
