### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by Leon99** [MHProDev/MHDDoS#233]
With latest docker:

[22:29:15 - WARNING] Thread is higher than 1000
[22:29:15 - WARNING] RPC (Request Pre Connection) is higher than 100
[22:29:15 - INFO] Proxy Count: 1,071
Traceback (most recent call last):
  File "/mhddos_proxy/MHDDoS/./start.py", line 1369, in <module>
    referers, proxies).start()
  File "/usr/local/lib/python3.10/threading.py", line 928, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by SudoLite** [comment]
u need more power

**Comment by Leon99** [comment]
@SudoLite what do you mean?

**Comment by SudoLite** [comment]
Give me information about server
Cpu?
memory?

**Comment by Leon99** [comment]
i5-11600, 32GB RAM

**Comment by Monkeyman1337s** [comment]
go restart your terminal it will work

**Comment by Leon99** [comment]
Looks like the reason was that I put too many 0s for -t :)
