### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by Ki4o112** [MHProDev/MHDDoS#252]
**Please complete the following information**
 - OS: [Kali linux]
 
** BUG **

Traceback (most recent call last):
  File "/home/xki4o/MHDDoS/start.py", line 1319, in <module>
    host = gethostbyname(url.host)
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xki4o/MHDDoS/start.py", line 1321, in <module>
    exit('Cannot resolve hostname ', url.host, e)
  File "/home/xki4o/MHDDoS/start.py", line 73, in exit
    logger.error(" ".join(message))
TypeError: sequence item 2: expected str instance, gaierror found

**Comment by Shesui** [comment]
Command please

**Comment by MHProDev** [comment]
python version ?
