### ISSUE TITLE
Windows executable?

### ISSUE THREAD

**Issue by Michal-Mikolas** [MHProDev/MHDDoS#253]
Is there a way to compile this into `.exe` ? 

I've tried with `auto-py-to-exe`, but running `bypass` attack failed: 
```
> ./mhddos.exe bypass https://example.com 5 101 socks5.txt 100 3600
Traceback (most recent call last):
  File "start.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "PyRoxy\GeoIP\__init__.py", line 7, in <module>
  File "maxminddb\__init__.py", line 69, in open_database
  File "maxminddb\reader.py", line 57, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\myusername\\AppData\\Local\\Temp\\_MEI22522\\PyRoxy\\GeoIP\\Sqlite\\GeoLite2-Country.mmdb'
[31620] Failed to execute script 'start' due to unhandled exception!
```

**Comment by Shesui** [comment]
IT'S NOT FOR WINDOWS WTF YOU DO GUY STOPPPPPP

**Comment by Michal-Mikolas** [comment]
Solved. Needed to add `--collect-all PyRoxy` parameter.
