### ISSUE TITLE
[BUG Report]:

### ISSUE THREAD

**Issue by Goksi** [MHProDev/MHDDoS#262]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Ubuntu 20.04.4 LTS
- Installed Requirements Version [MarkupSafe 2.1.1, Jinja2 3.0.3, itsdangerous 2.1.1, Werkzeug 2.0.3, click 8.0.4, multidict 6.0.2, mpacket 3.0.4, flask 2.0.3, pyOpenSSL 19.0.0, ldap3 2.9.1, ldapdomaindump 0.9.3, six 1.14.0, pycryptodomex, 3.14.1, pyasn1 0.4.8,  future 0.18.2,  idna 2.8, urllib3 1.23, pysocks 2.0.12, maxminddb 1.7.1, yarl 1.7.2, icmplib 3.0.3, psutil 5.9.0,  impacket 0.9.23, requests 2.27.1, dnspython 2.2.1, certifi 2019.11.28, cfscrape 2.1.1,  PyRoxy 1.0b4]
- Python Version Python 3.8.10
```

### What happened (Describe the bug) ?

```
[21:09:50 - INFO] Attack Started to ip with DNS method for 20 seconds, threads: 20!
Exception in thread Thread-6:
Exception in thread Thread-5:
Traceback (most recent call last):
Exception in thread Thread-1:
Exception in thread Thread-8:
Traceback (most recent call last):
Exception in thread Thread-11:
Traceback (most recent call last):
Exception in thread Thread-13:
Exception in thread Thread-18:
Traceback (most recent call last):
Traceback (most recent call last):
Exception in thread Thread-3:
Exception in thread Thread-9:
Traceback (most recent call last):
Exception in thread Thread-12:
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-19:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-10:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-14:
Exception in thread Thread-16:
Traceback (most recent call last):
Traceback (most recent call last):
Exception in thread Thread-20:
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "start.py", line 186, in run
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-15:
Traceback (most recent call last):
Exception in thread Thread-2:
Traceback (most recent call last):
    self.run()
  File "start.py", line 186, in run
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "start.py", line 186, in run
    self.select(self._method)
  File "start.py", line 235, in select
    self.run()
Traceback (most recent call last):
    self.run()
  File "start.py", line 186, in run
    self.run()
    self.run()
  File "start.py", line 186, in run
    self.select(self._method)
  File "start.py", line 235, in select
  File "start.py", line 186, in run
    self.run()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-4:
Traceback (most recent call last):
    self.run()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    self._amp_payloads = cycle(self._generate_amp())
    self.select(self._method)
    self.run()
  File "start.py", line 186, in run
  File "start.py", line 186, in run
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "start.py", line 186, in run
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 235, in select
    self.select(self._method)
    self.select(self._method)
  File "start.py", line 235, in select
  File "start.py", line 186, in run
  File "start.py", line 186, in run
    self.run()
  File "start.py", line 186, in run
  File "start.py", line 186, in run
    self.select(self._method)
  File "start.py", line 235, in select
  File "start.py", line 235, in select
    self.run()
  File "start.py", line 186, in run
    self.select(self._method)
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 186, in run
    self.select(self._method)
  File "start.py", line 235, in select
  File "start.py", line 332, in _generate_amp
    self.select(self._method)
  File "start.py", line 235, in select
    self.select(self._method)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
    self.select(self._method)
  File "start.py", line 235, in select
    self.select(self._method)
  File "start.py", line 235, in select
    for ref in self._ref:
  File "start.py", line 235, in select
    self._amp_payloads = cycle(self._generate_amp())
    self.select(self._method)
  File "start.py", line 235, in select
    self.run()
  File "start.py", line 186, in run
  File "start.py", line 332, in _generate_amp
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
TypeError: 'NoneType' object is not iterable
    self._amp_payloads = cycle(self._generate_amp())
    self.run()
  File "start.py", line 186, in run
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
    self._amp_payloads = cycle(self._generate_amp())
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
    self.run()
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
  File "start.py", line 235, in select
  File "start.py", line 332, in _generate_amp
  File "start.py", line 332, in _generate_amp
    self.run()
    for ref in self._ref:
    self.select(self._method)
  File "start.py", line 235, in select
    self.select(self._method)
  File "start.py", line 235, in select
    self.select(self._method)
    self._amp_payloads = cycle(self._generate_amp())
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
TypeError: 'NoneType' object is not iterable
    self._amp_payloads = cycle(self._generate_amp())
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
  File "start.py", line 235, in select
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
  File "start.py", line 332, in _generate_amp
    self.select(self._method)
  File "start.py", line 235, in select
    for ref in self._ref:
  File "start.py", line 186, in run
    for ref in self._ref:
    self._amp_payloads = cycle(self._generate_amp())
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    for ref in self._ref:
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
    self._amp_payloads = cycle(self._generate_amp())
TypeError: 'NoneType' object is not iterable
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
  File "start.py", line 332, in _generate_amp
    self.run()
  File "start.py", line 186, in run
    self._amp_payloads = cycle(self._generate_amp())
TypeError: 'NoneType' object is not iterable
TypeError: 'NoneType' object is not iterable
    for ref in self._ref:
  File "start.py", line 186, in run
TypeError: 'NoneType' object is not iterable
    self._amp_payloads = cycle(self._generate_amp())
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
  File "start.py", line 332, in _generate_amp
  File "start.py", line 332, in _generate_amp
    self.select(self._method)
  File "start.py", line 235, in select
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
    self.select(self._method)
TypeError: 'NoneType' object is not iterable
TypeError: 'NoneType' object is not iterable
    for ref in self._ref:
    self.select(self._method)
  File "start.py", line 235, in select
TypeError: 'NoneType' object is not iterable
  File "start.py", line 235, in select
    self._amp_payloads = cycle(self._generate_amp())
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
  File "start.py", line 332, in _generate_amp
    self._amp_payloads = cycle(self._generate_amp())
  File "start.py", line 332, in _generate_amp
    for ref in self._ref:
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable
TypeError: 'NoneType' object is not iterable
    for ref in self._ref:
TypeError: 'NoneType' object is not iterable

```
This error appears when I try to run script

### Screenshots

https://prnt.sc/Tx_havMlO7mc

**Comment by MHProDev** [comment]
you dns file is empty ?

**Comment by Goksi** [comment]
If you ask about hosts file, I have just 1 non-default record pointing to localhost
```

### Hetzner Online GmbH installimage
127.0.0.1 localhost.localdomain localhost
publicIPv4 Ubuntu-2004-focal-64-minimal-hwe
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
ff02::3 ip6-allhosts
publicIPv6 Ubuntu-2004-focal-64-minimal-hwe
127.0.0.1 localhost www.mydomain.com
```

**Comment by MHProDev** [comment]
:|

**Comment by MHProDev** [comment]
dns.txt in files directory

**Comment by Goksi** [comment]
I don't even have that file inside files dir

**Comment by MHProDev** [comment]
okye scan dns reflector and put into dns.txt
