### ISSUE TITLE
SyntaxError after last commit of start.py

### ISSUE THREAD

**Issue by alexnest-ua** [MHProDev/MHDDoS#280]
With Python:
![image](https://user-images.githubusercontent.com/74729549/159140855-5fef977d-5d0d-4532-b2e4-0da5c99dffb9.png)

azureuser@ubuntu-west-us:~/MHDDoS$ sudo python start.py bypass https://just-eat.by 5 1000 http.txt 100 100
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax

With python3:
![image](https://user-images.githubusercontent.com/74729549/159140863-f76e9531-dd77-4030-acff-79e0199fefb9.png)

azureuser@ubuntu-west-us:~/MHDDoS$ sudo python3 start.py bypass https://just-eat.by 5 1000 http.txt 100 100
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/usr/local/lib/python3.8/dist-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], str] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length))
                                                                                      ^
SyntaxError: invalid syntax

Tested different methods of attack - all have same error

**Comment by Noise13po** [comment]
same errors

**Comment by avapirev** [comment]
error confirmed after an update (git pull) 29/03/2022:

Traceback (most recent call last):
  File "mhddos_proxy/runner.py", line 12, in <module>
    from MHDDoS.start import ProxyManager, logger
  File "mhddos_proxy/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "miniconda3/envs/mhddos_proxy/lib/python3.10/site-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "miniconda3/envs/mhddos_proxy/lib/python3.10/site-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], str] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length))
                                                                                                            ^
SyntaxError: unmatched ')'

**Comment by MHProDev** [comment]
fixed https://github.com/MHProDev/PyRoxy/commit/897a7653821216ef1f72e0e2d35a3faf5099687c
