### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by h1xrrr** [MHProDev/MHDDoS#283]
### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
Traceback (most recent call last):
  File "/home/kali/MHDDoS/start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
  File "/home/kali/.local/lib/python3.9/site-packages/PyRoxy/__init__.py", line 13, in <module>
    from PyRoxy import GeoIP, Tools
  File "/home/kali/.local/lib/python3.9/site-packages/PyRoxy/Tools/__init__.py", line 18
    rand_char: Callable[[int], str] = lambda length=16: chr(Random.rand_int(0, 1000)) for _ in range(length))
```

### What happened (Describe the bug) ?

When i start the MHDDoS with this following script
python3 start.py tools or help 
this below problem happens 

### Screenshots

www.google.com

**Comment by SudoLite** [comment]
Fixed https://github.com/MHProDev/PyRoxy/commit/897a7653821216ef1f72e0e2d35a3faf5099687c
